# 💎⚡ HYPERFOCUS EMPIRE FUNDING CONFIGURATION ⚡💎
# Enable GitHub Sponsors button and support options

github: welshDog
patreon: hyperfocuszone
ko_fi: hyperfocuszone
custom: 
  - "https://hyperfocuszone.com/support"
  - "https://paypal.me/hyperfocuszone"
  - "mailto:SEND-ME.NFT@ud.me"
